/*
	DataUnsupportedLanguage.ts

	Copyright (c) 2014-2022 dangered wolf, et al
	Released under the MIT License
*/

export default {
	af:"U stelselstelsel word nog nie deur ModernDeck ondersteun nie. Help om te vertaal:",
	am:"የስርዓት ቋንቋዎ ገና በአገር ደረጃ ገና አይደገፍም። ለመተርጎም እገዛ:",
	ar:"لغة نظامك غير مدعومة أصلاً بواسطة ModernDeck حتى الآن. مساعدة في الترجمة:",
	az:"Sisteminizin dili hələ ModernDeck tərəfindən dəstəklənmir. Tərcümə etməyə kömək edin:",
	be:"Мова вашай сістэмы яшчэ не падтрымліваецца ModernDeck. Дапамажыце перакласці:",
	bn:"আপনার সিস্টেমের ভাষা মডার্নডেক দ্বারা এখনও স্থানীয়ভাবে সমর্থিত নয়। সহায়তা অনুবাদ:",
	bg:"Вашият системен език все още не се поддържа от ModernDeck. Помощ за превода:",
	bs:"Vaš sistemski jezik još nije izvorno podržan od strane ModernDeck-a. Pomoć za prevođenje:",
	ca:"ModernDeck encara no és compatible amb el vostre llenguatge del sistema. Ajuda a traduir:",
	co:"A vostra lingua di u sistema ùn hè micca sustegnu nativamente da ModernDeck. Aiutate à traduce:",
	cs:"Váš systémový jazyk není nativně podporován programem ModernDeck. Pomozte překládat:",
	cy:"Nid yw iaith eich system yn cael ei chefnogi'n frodorol gan ModernDeck eto. Helpwch i gyfieithu:",
	da:"Dit systemsprog understøttes endnu ikke af ModernDeck. Hjælp med at oversætte:",
	de:"Ihre Systemsprache wird von ModernDeck noch nicht nativ unterstützt. Hilfe beim Übersetzen:",
	el:"Η γλώσσα του συστήματός σας δεν υποστηρίζεται εγγενώς από το ModernDeck. Βοήθεια μετάφρασης:",
	en:"Your system language is not natively supported by ModernDeck yet. Help translate: ",
	eo:"Via sistema lingvo ankoraŭ ne estas subtenata de ModernDeck. Helpu traduki:",
	es:"El idioma de su sistema no es compatible de forma nativa con ModernDeck todavía. Ayuda a traducir:",
	et:"Teie süsteemikeelt ei toeta veel ModernDeck. Aidake tõlkida:",
	eu:"Oraindik ez duzu ModernDeck-ek onartzen zure sistemaren hizkuntza. Laguntza itzultzen:",
	fa:"زبان سیستم شما هنوز توسط ModernDeck پشتیبانی نمی شود. کمک به ترجمه:",
	fi:"ModernDeck ei vielä tue järjestelmäkieltäsi. Auta kääntämään:",
	fj:"Na nomu vosa ni ivakarau e sega ni natively tokoni mai vei ModernDeck. Veivuke me vakadewataki: ",
	fr:"Le langage de votre système n'est pas encore pris en charge nativement par ModernDeck. Aide à traduire:",
	fy:"Jo systeemtaal wurdt noch net natuerlik stipe troch ModernDeck. Help oersette:",
	ga:"Ní thacaíonn ModernDeck le teanga do chórais go dúchasach fós. Cuidigh le haistriú:",
	gd:"Chan eil cànan an t-siostaim agad a ’faighinn taic dhùthchasach bho ModernDeck fhathast. Cuidich le eadar-theangachadh:",
	gl:"ModernDeck aínda non é compatible co seu idioma do sistema. Axuda a traducir:",
	gu:"તમારી સિસ્ટમ ભાષા મૂળરૂપે હજી મોડર્નડેક દ્વારા સપોર્ટેડ નથી. ભાષાંતરમાં સહાય કરો:",
	ha:"ModernDeck ba shi da tallafi na asali. Taimaka fassara:",
	he:"שפת המערכת שלך עדיין לא נתמכת על ידי ModernDeck. עזרה בתרגום:",
	hi:"आपकी सिस्टम भाषा अभी तक ModernDeck द्वारा मूल रूप से समर्थित नहीं है। अनुवाद में मदद करें:",
	hr:"Jezik vašeg sustava ModernDeck još nije izvorno podržan. Pomoć za prevođenje:",
	ht:"Lang sistèm ou a pa sipòte pa ModernDeck ankò. Ede tradui:",
	hy:"Ձեր համակարգի լեզուն դեռ բնօրինակի չի աջակցում ModernDeck- ի կողմից: Օգնեք թարգմանել.",
	hu:"A ModernDeck még nem támogatja a rendszernyelv natív támogatását. Segíts a fordításban:",
	id:"Bahasa sistem Anda belum didukung oleh ModernDeck. Bantu menerjemahkan:",
	ig:"ModernDeck anaghị akwado asụsụ sistemụ gị. Nyere ntụgharị aka:",
	is:"ModernDeck styður ekki tungumál kerfisins þíns. Hjálpaðu okkur við að þýða:",
	it:"La lingua del tuo sistema non è ancora supportata nativamente da ModernDeck. Aiuta a tradurre:",
	ja:"ご使用のシステム言語は、ModernDeckではまだネイティブサポートされていません。 翻訳の手助け：",
	jv:"Bahasa sistem sampeyan durung didhukung kanthi asli dening ModernDeck. Pitulung nerjemahake:",
	ka:"თქვენი სისტემის ენა ჯერ არ არის მხარდაჭერილი ModernDeck– ით. დახმარება თარგმნეთ:",
	kk:"Сіздің жүйелік тіліңізді ModernDeck әлі қолдамайды. Аударуға көмек:",
	km:"ភាសាប្រព័ន្ធរបស់អ្នកមិនត្រូវបានគាំទ្រពីកំណើតដោយ ModernDeck នៅឡើយទេ។ ជួយបកប្រែ៖",
	kn:"ನಿಮ್ಮ ಸಿಸ್ಟಮ್ ಭಾಷೆಯನ್ನು ಇನ್ನೂ ಸ್ಥಳೀಯವಾಗಿ ModernDeck ಬೆಂಬಲಿಸುವುದಿಲ್ಲ. ಭಾಷಾಂತರಿಸಲು ಸಹಾಯ ಮಾಡಿ:",
	ko:"시스템 언어는 아직 ModernDeck에서 기본적으로 지원되지 않습니다. 번역 도움말 :",
	ku:"Zimanê pergala te ji hêla ModernDeck ve hîn nebûye piştgirî. Alîkarî wergerandin:",
	ky:"Системалык тилиңиз ModernDeck тарабынан азырынча колдоого алынбайт. Которууга жардам бериңиз:",
	la:"Tua ratio linguae, non tamen paternus subnixus ModernDeck. Auxilium interpretari:",
	lb:"Är System Sprooch gëtt nach net vum ModernDeck ënnerstëtzt. Hëlleft Iwwersetze:",
	lo:"ພາສາລະບົບຂອງທ່ານຍັງບໍ່ທັນໄດ້ຮັບການສະ ໜັບ ສະ ໜູນ ຈາກພາສາ ModernDeck ເທື່ອ. ຊ່ວຍແປ:",
	lt:"ModernDeck dar nepalaiko jūsų sistemos kalbos. Padėkite išversti:",
	lv:"ModernDeck jūsu sistēmas valodu vēl neatbalsta. Palīdziet tulkot:",
	mi:"Kaore ano te reo o to rohe e tautokohia ana e te ModernDeck. Āwhina whakamāori:",
	mk:"Вашиот системски јазик сеуште не е поддржан од ModernDeck. Помогне за превод:",
	ml:"നിങ്ങളുടെ സിസ്റ്റം ഭാഷയെ ഇതുവരെ ModernDeck പിന്തുണയ്‌ക്കുന്നില്ല. വിവർത്തനം ചെയ്യാൻ സഹായിക്കുക:",
	mg:"Ny fitenin'ny rafitrasao dia tsy vazaha teratany amin'ny ModernDeck. Hanampy handika:",
	mn:"Таны системийн хэлийг ModernDeck хэлээр хараахан дэмжихгүй байна. Орчуулахад туслах:",
	mr:"आपल्या सिस्टम भाषेस अद्याप मूळ रूपात ModernDeck द्वारे समर्थित नाही. भाषांतर मदत करा:",
	ms:"Bahasa sistem anda belum disokong oleh ModernDeck secara asli. Bantu terjemahkan:",
	mt:"Il-lingwa tas-sistema tiegħek għadha mhix appoġġata b'mod indiġenu minn ModernDeck. Għajnuna fit-traduzzjoni:",
	my:"သင်၏ system language ကို ModernDeck မှမူလအတိုင်းမထောက်ပံ့သေးပါ။ ဘာသာပြန်ကိုကူညီပါ။",
	ne:"तपाईंको प्रणाली भाषा मूल रूप मा ModernDeck द्वारा समर्थित छैन। मद्दत अनुवाद:",
	nl:"Uw systeemtaal wordt nog niet standaard door ModernDeck ondersteund. Help vertalen:",
	no:"Systemspråket ditt støttes ikke av ModernDeck ennå. Hjelp til å oversette:",
	ny:"Zilankhulo zanu sizothandiziridwa mwapadera ndi ModernDeck panobe. Thandizani kutanthauzira:",
	or:"ଆପଣଙ୍କର ସିଷ୍ଟମ୍ ଭାଷା ଏପର୍ଯ୍ୟନ୍ତ ModernDeck ଦ୍ୱାରା ସମର୍ଥିତ ନୁହେଁ | ଅନୁବାଦ କରିବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ:",
	pa:"ਤੁਹਾਡੀ ਸਿਸਟਮ ਭਾਸ਼ਾ ਅਜੇ ਮੂਲ ਰੂਪ ਵਿੱਚ ModernDeck ਦੁਆਰਾ ਸਮਰਥਤ ਨਹੀਂ ਹੈ. ਸਹਾਇਤਾ ਅਨੁਵਾਦ:",
	pl:"Twój język systemowy nie jest jeszcze obsługiwany przez ModernDeck. Pomóż przetłumaczyć:",
	ps:"ستاسو د سیسټم ژبه په اصلي ډول د ModernDeck لخوا ملاتړ شوې نده. مرسته ژباړل:",
	pt:"O idioma do sistema ainda não é suportado nativamente pelo ModernDeck. Ajude a traduzir:",
	ro:"Limba dvs. de sistem nu este încă acceptată nativ de ModernDeck. Ajutor pentru traducere:",
	ru:"Ваш системный язык еще не поддерживается ModernDeck. Помогите перевести:",
	rw:"Ururimi rwa sisitemu ntabwo rushyigikiwe na ModernDeck kugeza ubu. Gufasha guhindura:",
	sd:"توھانجي سسٽم جي ٻولي اصلي طور تي تعاون ٿيل ناھي ModernDeck اڃا تائين. مدد ڪريو ترجمو:",
	si:"ඔබේ පද්ධති භාෂාවට ස්වදේශීයව සහාය නොදක්වයි ModernDeck තවම. පරිවර්තනය කිරීමට උදව් කරන්න:",
	sk:"Váš systémový jazyk nie je natívne podporovaný ModernDeck ešte. Pomôžte s prekladom:",
	sl:"Jezik vašega sistema izvorno ne podpira ModernDeck še. Pomoč pri prevajanju:",
	sm:"O lau gagana gagana e le o lagolagoina ile ModernDeck. Fesoasoani faaliliu:",
	sn:"Mutauro wako wechirongwa hausiko kutsigirwa nawo ModernDeck zvakadaro. Batsira kududzira:",
	so:"Luuqadaada nidaamku asal ahaan kuma taageeraan ModernDeck weli. Caawinta tarjumida:",
	sq:"Gjuha juaj e sistemit nuk mbështetet ende nga ModernDeck akoma. Ndihmoni në përkthimin:",
	sr:"ModernDeck системски језик још не подржава изворно. Помоћ за превођење:",
	st:"Puo ea sistimi ea hau ha e ts'ehetsoe ka tlhaho ke ModernDeck. Thusa ho fetolela:",
	su:"Bahasa sistem anjeun henteu didukung asli ModernDeck acan. Pitulung narjamahkeun:",
	sv:"Ditt systemspråk stöds inte av ModernDeck ännu. Hjälp med att översätta:",
	sw:"Lugha ya mfumo wako haihimiliwi na ModernDeck bado. Saidia kutafsiri:",
	ta:"உங்கள் கணினி மொழி இதற்கு சொந்தமாக ஆதரிக்கப்படவில்லை ModernDeck இன்னும். மொழிபெயர்க்க உதவுங்கள்:",
	te:"మీ సిస్టమ్ భాషకు స్థానికంగా మద్దతు లేదు ModernDeck ఇంకా. అనువదించడానికి సహాయం చేయండి:",
	th:"ภาษาระบบของคุณไม่ได้รับการสนับสนุนโดยกำเนิด ModernDeck ช่วยแปล:",
	tk:"Ulgam diliňiz aslynda goldanylmaýar ModernDeck. Terjime etmäge kömek:",
	tl:"Ang iyong wika wika ay hindi katutubong suportado ng ModernDeck pa. Tulong sa pagsasalin:",
	tg:"Забони системавии шумо бо дастгирии маҳаллӣ дастгирӣ намешавад ModernDeck ҳанӯз. Кӯмак ба тарҷума:",
	tr:"Sistem diliniz yerel olarak tarafından desteklenmiyor ModernDeck henüz. Çeviriye yardım et:",
	tt:"Сезнең система теле туган якта булмый ModernDeck әле. Тәрҗемә итүдә булыш:",
	uk:"Мова вашої системи не підтримується вродженою ModernDeck поки. Допоможіть перекласти:",
	ug:"سىستېما تىلىڭىزنى يەرلىك قوللىمايدۇ ModernDeck تېخى. تەرجىمە ياردەم:",
	ur:"آپ کے سسٹم کی زبان کو مقامی طور پر تائید حاصل نہیں ہےابھی تک ModernDeck. ترجمہ میں مدد کریں:",
	uz:"Tizim tili ona tomonidan qo'llab-quvvatlanmaydi ModernDeck hali. Tarjimaga yordam bering:",
	vi:"Ngôn ngữ hệ thống của bạn không được hỗ trợ bởi ModernDeck chưa. Trợ giúp dịch:",
	xh:"Ulwimi lwenkqubo yakho aluxhaswanga ngokwemveli ModernDeck okwangoku. Nceda uguqulele:",
	yi:"דיין סיסטעם שפּראַך איז נישט געבוירן געבוירן דורך ModernDeck נאָך. הילף איבערזעצן:",
	yo:"Ede eto rẹ ko jẹ ti abinibi nipasẹ ModernDeck sibẹsibẹ. Iranlọwọ pese:",
	zh:"ModernDeck尚不支持您的系統語言。 幫助翻譯：",
	zu:"Ulimi lohlelo lwakho alwesekelwa ngabomdabu I-ModernDeck kuze kube manje. Siza ukuhumusha:",
}
